export const ACTIONS = {
  LOAD_BANK_STATEMENT: 'loadBankStatement',
};

export const GETTERS = {
  FULL_BANK_STATEMENT: 'fullBankStatement',
  CATEGORIES_WITH_TOTAL: 'categoriesWithTotal',
  TOTAL_AMOUNT: 'totalAmount',
};

export const MUTATIONS = {
  SET_BANK_STATEMENT: 'SET_BANK_STATEMENT',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
};

export const MODULES = {
  BANK_STATEMENT: 'bankStatement',
};

export const BANK_STATEMENT_STORE = {
  //GETTERS
  FULL_STATEMENT: `${MODULES.BANK_STATEMENT}/${GETTERS.FULL_BANK_STATEMENT}`,
  TOTAL_AMOUNT: `${MODULES.BANK_STATEMENT}/${GETTERS.TOTAL_AMOUNT}`,
  CATEGORIES_WITH_TOTAL: `${MODULES.BANK_STATEMENT}/${GETTERS.CATEGORIES_WITH_TOTAL}`,
  //MUTATIONS
  UPDATE_AMOUNT: `${MODULES.BANK_STATEMENT}/${MUTATIONS.UPDATE_AMOUNT}`,
  //ACTIONS
  LOAD_FULL_STATEMENT: `${MODULES.BANK_STATEMENT}/${ACTIONS.LOAD_BANK_STATEMENT}`,
};
